// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FullCartAPI.Models;

public partial class Log
{
    public int Id { get; set; }

    public string Container { get; set; }

    public string FunctionName { get; set; }

    public string CaseName { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime? CreatedAt { get; set; }
}